# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: 'Jira to Roadmap sync'

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - jira-automation/

pr:
  paths:
    include:
      - jira-automation/

schedules:
  - cron: '0 8-17 * * Mon-Fri'
    displayName: Runs once every hour during business hours, Monday through Friday
    branches:
      include:
        - master
    always: 'true'

pool:
  name: 'hmcts-cftptl-agent-pool'

steps:
  - task: AzureKeyVault@2
    displayName: "Get GitHub API token from Key Vault"
    inputs:
      runAsPreJob: false
      ConnectedServiceName: "DTS-CFTPTL-INTSVC"
      keyVaultName: "cftptl-intsvc"
      secretsFilter: "github-roadmap-token,jira-api-token"
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
    displayName: 'npm install'
    workingDirectory: jira-automation
  - task: Bash@3
    displayName: 'Importing issues'
    env:
      GITHUB_TOKEN: $(github-management-api-token)
      JIRA_API_TOKEN: $(jira-api-token)
    inputs:
      targetType: inline
      script: node jira-automation/index.mjs
