---
name: 'Jira to Roadmap sync - Created'
trigger: none
pr: none

resources:
  webhooks:
    - webhook: JiraPlatformOperationsRoadmapCreated
      connection: JiraPlatformOperationsRoadmapCreated

pool:
  name: 'hmcts-cftptl-agent-pool'

steps:
  - task: AzureKeyVault@2
    displayName: "Get GitHub API token from Key Vault"
    inputs:
      runAsPreJob: false
      ConnectedServiceName: "DTS-CFTPTL-INTSVC"
      keyVaultName: "cftptl-intsvc"
      secretsFilter: "github-management-api-token,jira-api-token,github-roadmap-private-key,github-roadmap-app-id"
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
    displayName: 'npm install'
    workingDirectory: jira-automation
  - task: Bash@3
    displayName: 'Creating issue'
    env:
      GITHUB_TOKEN: $(github-management-api-token)
      JIRA_API_TOKEN: $(jira-api-token)
      JIRA_ISSUE_KEY: '${{ parameters.JiraPlatformOperationsRoadmapCreated.key }}'
      GITHUB_APP_ID: $(github-roadmap-app-id)
      GITHUB_APP_PRIVATE_KEY: |
        $(github-roadmap-private-key)
    inputs:
      targetType: inline
      script: node jira-automation/create-issue.mjs
