# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'hmcts-cftptl-agent-pool'

steps:
  - task: AzureKeyVault@2
    displayName: "Get GitHub API token from Key Vault"
    inputs:
      runAsPreJob: false
      ConnectedServiceName: "DTS-CFTPTL-INTSVC"
      keyVaultName: "cftptl-intsvc"
      secretsFilter: "github-management-api-token,jira-api-token"
  - task: Bash@3
    displayName: 'Importing issues'
    env:
      GITHUB_TOKEN: $(github-management-api-token)
      JIRA_API_TOKEN: $(jira-api-token)
    inputs:
      targetType: filePath
      filePath: jira-automation/index.mjs
