---
name: 'Jira to Roadmap sync - Complete issue'
trigger: none
pr: none

resources:
  webhooks:
    - webhook: JiraPlatformOperationsRoadmapDone
      connection: JiraPlatformOperationsRoadmapDone

steps:
  - task: AzureKeyVault@2
    displayName: "Get GitHub API token from Key Vault"
    inputs:
      runAsPreJob: false
      ConnectedServiceName: "DTS-CFTPTL-INTSVC"
      keyVaultName: "cftptl-intsvc"
      secretsFilter: "jira-api-token,github-roadmap-private-key,github-roadmap-app-id"
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
    displayName: 'npm install'
    workingDirectory: jira-automation
  - task: Bash@3
    displayName: 'Updating issue to done'
    env:
      JIRA_API_TOKEN: $(jira-api-token)
      JIRA_ISSUE_KEY: '${{ parameters.JiraPlatformOperationsRoadmapDone.key }}'
      GITHUB_APP_ID: $(github-roadmap-app-id)
      GITHUB_APP_PRIVATE_KEY: |
        $(github-roadmap-private-key)
    inputs:
      targetType: inline
      script: node jira-automation/update-issue-done.mjs
