name: Move Issue to ✅ Done When Closed

on:
  issues:
    types: [closed]

permissions:
  contents: read
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  move-to-done:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI and jq
        run: |
          sudo apt update
          sudo apt install -y gh jq

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: hmcts

      - name: Authenticate GitHub CLI
        run: echo "${{ steps.generate_token.outputs.token }}" | gh auth login --with-token

      - name: Move issue to ✅ Done
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          PROJECT_OWNER: hmcts
          PROJECT_NUMBER: 10
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          echo "Getting project ID..."
          PROJECT_ID=$(gh project view "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --format json | jq -r '.id')
          echo "PROJECT_ID: $PROJECT_ID"

          echo "Fetching project fields..."
          FIELDS=$(gh project field-list "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --format json)
          STATUS_FIELD=$(echo "$FIELDS" | jq -r '.[] | select(.name == "Status")')
          STATUS_FIELD_ID=$(echo "$STATUS_FIELD" | jq -r '.id')
          DONE_OPTION_ID=$(echo "$STATUS_FIELD" | jq -r '.options[] | select(.name == "✅ Done") | .id')

          echo "STATUS_FIELD_ID: $STATUS_FIELD_ID"
          echo "DONE_OPTION_ID: $DONE_OPTION_ID"

          echo "Fetching project items..."
          ITEMS=$(gh project item-list "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --format json --limit 100)

          ITEM_ID=$(echo "$ITEMS" | jq -r --arg ISSUE_NUMBER "$ISSUE_NUMBER" '.[] | select(.content.number == ($ISSUE_NUMBER | tonumber)) | .id')

          if [ -n "$ITEM_ID" ]; then
            echo "Found item ID: $ITEM_ID"
          else
            echo "Issue not found in project. Skipping."
            exit 0
          fi

          echo "Updating issue status to ✅ Done..."
          RESULT=$(gh project item-edit "$PROJECT_NUMBER" \
            --id "$ITEM_ID" \
            --project-id "$PROJECT_ID" \
            --field-id "$STATUS_FIELD_ID" \
            --single-select-option-id "$DONE_OPTION_ID" \
            --format json)

          if echo "$RESULT" | jq -e '.id' > /dev/null; then
            echo "✅ Issue successfully updated to ✅ Done."
          else
            echo "❌ Error updating issue status."
            exit 1
          fi
